[book]
authors = ["JLer"]
language = "zh"
multilingual = false
src = "guide/src"
title = "Async Raft"
description = "The async-raft user guide."

[build]
build-dir = "guide/book"
create-missing = false
